### ISSUE TITLE
[Bug] [MGS2 & MGS3]: Controller does not work on 2.0.0 cracked version 

### ISSUE THREAD

**Issue by FCGre** [Lyall/MGSHDFix#112]
Is there a solution or fix for using the XBOX controller in the cracked version?

**Comment by LethalPlacebo** [comment]
No support is offered for cracked versions of the games. As of 1.5.0, these games rely on Steam Input for their controller support. Without that, controllers won't work at all.

**Comment by FCGre** [comment]
> No support is offered for cracked versions of the games. As of 1.5.0, these games rely on Steam Input for their controller support. Without that, controllers won't work at all.

I don't have any access to buy games because of the sanctions, so I have to use cracked versions. I don't like it, but I have no choice. Is there any solution to use a controller?

**Comment by LethalPlacebo** [comment]
> > No support is offered for cracked versions of the games. As of 1.5.0, these games rely on Steam Input for their controller support. Without that, controllers won't work at all.
> 
> I don't have any access to buy games because of the sanctions, so I have to use cracked versions. I don't like it, but I have no choice. Is there any solution to use a controller?

I'm sorry to hear that. I'll give you a suggestion: try adding the games to Steam as non-Steam games. Make sure you have controller support for your controller type enabled. Then try and play.

This may or may not work because these games use a specific configuration in Steam Input that doesn't seem to be available for all games, but I suppose it's worth a shot.

**Comment by Lyall** [comment]
Buy the game, otherwise Konami is never gonna port MGS4 to PC 😭
