### ISSUE TITLE
How does this fix compare to MGSResolutionPatch?

### ISSUE THREAD

**Issue by Darthagnon** [Lyall/MGSHDFix#9]
[MGSResolutionPatch](https://github.com/Sergeanur/MGSResolutionPatch) is another project that aims to do the same thing as this one. I was wondering which is better, or if there were any key differences?

Related issues:
https://github.com/Sergeanur/MGSResolutionPatch/issues/10

**Comment by ShizCalev** [comment]
MGSR is essentially broken for MGS2 since it doesn't scale any of the UI elements, it really only fixes MGS3.

This patch also corrects the game's aspect ratio when you're set to a 16:9 resolution but you're using a monitor that supports a 17:9 (which adds black bars to the sides of your screen, an issue that's pr sent in deus ex and gta5 as well)

It also adds borderless windowed support, and lets you disable the mouse cursor.

**Comment by fashionableDark** [comment]
> MGSR is essentially broken for MGS2 since it doesn't scale any of the UI elements

The author fixed some of those today, including the codec static.
